// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHglWlC_37Pi23WI24eHI6KcdfNwethM4',
    appId: '1:904022408867:web:6506710473f3bf09cf4916',
    messagingSenderId: '904022408867',
    projectId: 'citiguid-8dcb2',
    authDomain: 'citiguid-8dcb2.firebaseapp.com',
    storageBucket: 'citiguid-8dcb2.firebasestorage.app',
    measurementId: 'G-PL5B75PKY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwnN48HgerLz8zCi_zLLND-8EET6-yYfA',
    appId: '1:904022408867:android:a15c48d2ac9a2154cf4916',
    messagingSenderId: '904022408867',
    projectId: 'citiguid-8dcb2',
    storageBucket: 'citiguid-8dcb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi9Pej-UsxWav3plyldgbkjlYgc66pzS4',
    appId: '1:904022408867:ios:257a8e7bc8da3a15cf4916',
    messagingSenderId: '904022408867',
    projectId: 'citiguid-8dcb2',
    storageBucket: 'citiguid-8dcb2.firebasestorage.app',
    iosBundleId: 'com.example.citiguid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi9Pej-UsxWav3plyldgbkjlYgc66pzS4',
    appId: '1:904022408867:ios:257a8e7bc8da3a15cf4916',
    messagingSenderId: '904022408867',
    projectId: 'citiguid-8dcb2',
    storageBucket: 'citiguid-8dcb2.firebasestorage.app',
    iosBundleId: 'com.example.citiguid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHglWlC_37Pi23WI24eHI6KcdfNwethM4',
    appId: '1:904022408867:web:a33fd700b131721acf4916',
    messagingSenderId: '904022408867',
    projectId: 'citiguid-8dcb2',
    authDomain: 'citiguid-8dcb2.firebaseapp.com',
    storageBucket: 'citiguid-8dcb2.firebasestorage.app',
    measurementId: 'G-8XES46QS8N',
  );
}
